---
# tasks file for serial-console


- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "os-{{ ansible_distribution }}.yml"
   - "os-default.yml"
  tags: serial_console


- name: "os scecific | included tasks"
  include: "{{ task_item }}"
  with_items: "{{ serial_console_tasks }}"
  loop_control:
    loop_var: task_item
  tags: serial_console
