---
- name: "serial-console| unsuported os"
  debug:
    msg: "Your system is not supported. Create vars/os-{{ os_version }}.yml"
  with_items:
  - "{{ ansible_distribution }}-{{ ansible_distribution_release }}"
  - "{{ ansible_distribution }}-{{ ansible_distribution_version }}"
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
  - "{{ ansible_distribution }}"
  loop_control:
    loop_var: os_version
  tags: serial_console
